title: My GitHub Blog
author: Cathy Scilla
email: cathyrunham@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My experiences on learning all about GitHub!
  From complete beginner to expert

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
